media:
  input: uploads
  output: /uploads

collections:
  - name: apks
    label: APK Applications
    path: content/apks
    type: folder
    format: json
    fields:
      - name: title
        label: App Name
        type: string
      - name: version
        label: Version (e.g. 1.0.0)
        type: string
      - name: category
        label: Category
        type: select
        options:
          - Apps
          - Games
          - Tools
      - name: icon
        label: App Icon
        type: image
      - name: description
        label: Description
        type: text
      - name: apk_file
        label: APK File (Under 100MB)
        type: file
      - name: external_link
        label: External Link (If APK > 100MB)
        type: string
        
